# Generated by Django 5.2 on 2025-05-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(unique=True)),
                ('cat_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=255)),
                ('book_image', models.ImageField(upload_to='')),
                ('book_slug', models.SlugField(max_length=100, unique=True)),
                ('Book_auther', models.CharField(max_length=255)),
                ('Book_price', models.PositiveIntegerField()),
                ('Book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
    ]
