# Generated by Django 5.2 on 2025-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_category',
            field=models.CharField(choices=[('fiction', 'نخیلی'), ('non-fiction', 'داستان واقعی'), ('biography', 'بیوگرافی'), ('science', 'علمی'), ('history', 'تاریخی'), ('fantasy', 'فانتزی'), ('romance', 'رومانتیک'), ('mystery', 'رازالود'), ('children', 'مناسب کودکان'), ('other', 'موضوعات دیگر')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
