# Generated by Django 5.1.3 on 2025-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=255)),
                ('Book_description', models.TextField(null=True)),
                ('Book_auther', models.CharField(max_length=255)),
                ('Book_category', models.CharField(choices=[('Fiction', 'علمی_تخیلی'), ('Non-Fiction', 'غیر_داستانی'), ('Biography', 'بیوگرافی'), ('Science', 'علمی'), ('History', 'تاریخی'), ('Fantasy', 'فانتزی'), ('Romance', 'رمانتیک'), ('Mystery', 'معمایی'), ("Children's Books", 'کتاب کودکان'), ('Other', 'غیره')], max_length=255, unique=True)),
                ('Book_price', models.PositiveIntegerField()),
                ('Book_slug', models.SlugField(max_length=500, unique=True)),
            ],
        ),
    ]
