# Generated by Django 5.1.3 on 2025-07-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_slug',
            field=models.SlugField(blank=True, editable=False, max_length=500, unique=True),
        ),
    ]
