# Generated by Django 5.2 on 2025-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='book',
            name='Book_category',
            field=models.CharField(choices=[('fiction', 'تخیلی'), ('non-fiction', 'داستان واقعی'), ('biography', 'بیوگرافی'), ('science', 'علمی'), ('history', 'تاریخی'), ('fantasy', 'فانتزی'), ('romance', 'رومانتیک'), ('mystery', 'رازالود'), ('children', 'مناسب کودکان'), ('other', 'موضوعات دیگر')], max_length=255),
        ),
    ]
